### ISSUE TITLE
Starting member with dynamically allocated port 

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube#14]
Motivation: streamline testing and development and deployments with zero configuration. 

the enhancement is to enable creating instance without specifying specific port 

Current:
....
ICluster clusterA = Cluster.newInstance(3000).join();
ICluster clusterA = Cluster.newInstance(3001).join();
....

After enhancement it will be possible to run on same  vm several cluster instances:
... 
ICluster clusterA = Cluster.newInstance().join();  -- > starts on default port
ICluster clusterB = Cluster.newInstance().join();  ---> starts on default port +1
...

**Comment by antonkharenko** [comment]
Actually if you run this code right now:

ICluster clusterA = Cluster.newInstance().join();

It will start transport on default port 29001.

**Comment by ronenhamias** [comment]
Dynamically allocated means on nodes start on default port 29001 + 1
After enhancement it will be possible to run on same vm several cluster instances:
... 
ICluster clusterA = Cluster.newInstance().join(); -- > starts on default port
ICluster clusterB = Cluster.newInstance().join(); ---> starts on default port +1

**Comment by myroslavlisniak** [comment]
We can do dynamically allocated ports, but there is one problem here.
Cluster creates transport instance in newInstance() method, but start in join() method.
This will cause situation when next code will not work as expected
```java
for (int i = 0; i < 10; i++) {
      clusters.add(Cluster.newInstance());
    }
 for (ICluster cluster : clusters) {
      cluster.joinAwait();
    }
```

I wonder why we really need to separate newInstance from join?
@antonkharenko @ronenhamias WDYT?

**Comment by ronenhamias** [comment]
IMHO there are 2 options:

Option 1 (base port)
ICluster clusterA = Cluster.newInstance(3000).join(); // start on port 3000
ICluster clusterB = Cluster.newInstance(3000).join(); // start on port 3001 since 3000 is taken.

Option 2 (port 0)
it means that these 2 lines are the same:
ICluster clusterA = Cluster.newInstance().join(); 
ICluster clusterA = Cluster.newInstance(0).join();

**Comment by kshchepanovskyi** [comment]
Don't you think that this approach might lead to unpredictable behavior?
Zero configuration == good defaults, but it does not mean "find some random port just to do not fail". 
What if some other application already uses this port (for example, old server instance that was not killed / stuck), and correct behavior in this case should be just fail to start?

**Comment by kshchepanovskyi** [comment]
@antonkharenko

Ok, with "automatic cluster node discovery" - similar to [Hazelcast's](http://docs.hazelcast.org/docs/3.5/manual/html/hazelcastclusters.html) multicast/tcp - it might be good idea.

Anyway, there still are few tricky moments.

1. Hazelcast always check if service that listens on remote port is actually hazelcast.
2. Hazelcast has a concept of "cluster name". Cluster nodes should check remote node's "cluster name" so that they are confident they do not connect to wrong node.

That's why I consider this feature danger.

> Motivation: streamline testing and development and deployments with zero configuration.

If we do not handle all corner cases, instead of improving things we can make them only worse.

**Comment by antonkharenko** [comment]
@kshchepanovskyi Basically automatic node discovery is supported  via seed members (it means you need to provide address of at least one existing node on cluster join to discover all other nodes in the cluster). It is not supported multicast discovery (as for now) since it I am not sure it has much value outside of demo or dev environment - multicast often disabled.

Also we have the concept of "cluster name" too. It is called "syncGroup" and it is a part of cluster configuration (ClusterConfiguration.ClusterMembershipSettings.syncGroup) which you can set to arbitrary string identifier. In addition to that Transport send handshake messages on connect so basically node on the other end need to run Transport too in order to pass handshake.

**Comment by antonkharenko** [comment]
Done at PR: https://github.com/scalecube/scalecube/pull/57
