### ISSUE TITLE
Transport port binding issues causing "TransportBrokenException: Detected duplicate.."

### ISSUE THREAD

**Issue by antonkharenko** [scalecube/scalecube#55]
Transport binds and listen to all network interfaces (0.0.0.0) for specific port. On the other hand it defines its address using IpAddressResolver.resolveIpAddress()  which determines local IP by looping over NetworkInterface.networkInterfaces() and taking first one IPv4 interface (excluding loopback). This is not good, because networkInterfaces() doesn't guarantee order of returning collection. This IP address then used by cluster membership. But seed members can use another network interface to connect to the same endpoint so from the point of Cluster it will be viewed as a separate addresses, but they will lead to same endpoint which causes as a result "TransportBrokenException: Detected duplicate...".

**Case 1. Several network interfaces (NI)**

On member there're 2 network interfaces. One private, one external. Our code in TransportFactory listens both interfaces.

From logs:
``` 
I 0727-1325:09,312 c.p.o.c.t.i.ExceptionCaughtChannelHandler Broken transport: NettyTransport{status=CONNECTED, channel=[id: 0x7ba35e97, /10.144.178.10:35789 => /10.144.176.10:4830]}, cause: TBE: Detected duplicate NettyTransport{status=READY, channel=[id: 0xbe66e44b, /172.31.178.10:57668 => /172.31.176.10:4830]} for key=tcp://172.31.178.10:4830 in accepted_map [oapi-transport-io-0@tcp://172.31.176.10:4830]
```

Caused by the following flow:
* Established conn 10.144.178.10:35789 => /10.144.176.10:4830 – but local address is tcp://172.31.176.10:4830 (as you can see from thread name), it means Transport listens both *.144 and *.31 addresses.
* Then duplicate detected because there's already - NettyTransport{status=READY, channel=[id: 0xbe66e44b, /172.31.178.10:57668 => /172.31.176.10:4830]}  under key tcp://172.31.178.10:4830 (i.e. connection was established earlier by interface with IP *.31, but connect attempt is made using  interface with IP *.144).

**Case 2. DNS names not supported**

*Env:* 2 nodes with 1 NI each.

*Conditions:* both nodes restarted.

*What happens:* From node 1 to node 2 transport (port=59915) established, after that the new transport (port 59916) is attempting to establish, which results in TBE (duplicates not allowed: there's already 59915).

From logs:
```
I 0728-1135:13,753 i.n.h.l.LoggingHandler [id: 0xe634f142, /172.29.49.109:59915 => app10.scalecube.io/172.29.49.177:4830] ACTIVE [oapi-transport-io-0@tcp://172.29.49.109:4830]
...
I 0728-1135:14,009 i.n.h.l.LoggingHandler [id: 0xebc94f97, /172.29.49.109:59916 => /172.29.49.177:4830] ACTIVE [oapi-transport-io-0@tcp://172.29.49.109:4830]
```
Note: putting IP addresses instead of DNS names to seed members addresses on  cluster initialization fixing this issue all together.

**Comment by artem-v** [comment]
PR https://github.com/scalecube/scalecube/pull/60 fixing problem with **Case 2. DNS names not supported**

**Comment by artem-v** [comment]
Upon **Case 1. Several network interfaces (NI)**. Describing a case with 2 NICs and appl listening on ``0.0.0.0``; so, there are 2 NICs -- one with primary IP (or call it _public_ or _external_) and another NIC with private IP (say for allowing dev ops to connect by ssh): 
* transport1 est. its local endpoint to a public IP and connects to transport2 onto its private IP; next time transport1 decides to connnect to transport2 by its public IP he would connect with no problem and  transport2 would perfectly detect _duplication_ scenario.
* transport1 est. its local endpoing to a public IP, transport2 est. its local endpoint to a private IP because ``IpAddressResolver`` found IP on private NIC;  then trasnport2 connects to transport1 onto its public IP, so far, at connection phase, all is well, but handshake exchange would not be fair: transport1 would be setup with accepted trasnport2 channel with its private IP, so msgs comming from transport2 would contain its private IP.

To battle this mess we need: 

1. Put in config only dns addresses or public IPs (well, better dns addresses).
2. Get rid of ``IpAddressResolver``, use ``InetAddress.getLocalhost()`` instead **and** ensure returned hostname is publicly available (**plus** make sure it's not ``localhost``, not ``127.0.0.1`` and not ``127.0.1.1``).
3. Wipe out  guarantee on system behaviour when:  **a)** smbdy puts private IP in cfg;   **b)** ``InetAddress.getLocalhost()`` doesn't return publicly available hostname/IP.

**Comment by artem-v** [comment]
A **Case 1. Several network interfaces (NI)** have been fixed in https://github.com/scalecube/scalecube/pull/60/commits/15f3346701cb2eb08b4ee0dece93b6f5510b0cb6

**Comment by myroslavlisniak** [comment]
Hi guys, are you aware about netty 4.1 new async dns resolver:
https://twitter.com/trustin/status/521630128086863872
Some example : https://gist.github.com/paiv/9c7b8629fbf686deb9d7

**Comment by artem-v** [comment]
@myroslavlisniak yes, but we are not yet ready to adopt netty 4.1

**Comment by antonkharenko** [comment]
Issue won't be relevant after merging PR: https://github.com/scalecube/scalecube/pull/69
